version: "3.9"

services:
  userge:
    container_name: userge
    build:
      context: .
      dockerfile: Dockerfile
    command: bash ./run 
    restart: on-failure
    environment:
      CURL: $CURL
    env_file:
      - config.env

  mongo:
      image: mongo
      volumes:
        - mongo_userge:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo_userge: